/// Flutter icons HomeAlone
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeAlone
///      fonts:
///       - asset: fonts/HomeAlone.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HomeAloneIcons {
  HomeAloneIcons._();

  static const _kFontFam = 'HomeAlone';

  static const IconData home_alone_logo =
      IconData(0xe816, fontFamily: _kFontFam);
  static const IconData arrow_circle_right =
      IconData(0xe900, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe901, fontFamily: _kFontFam);
  static const IconData challenges_fill =
      IconData(0xe902, fontFamily: _kFontFam);
  static const IconData challenges_outline =
      IconData(0xe903, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe904, fontFamily: _kFontFam);
  static const IconData creativity = IconData(0xe905, fontFamily: _kFontFam);
  static const IconData culinary = IconData(0xe906, fontFamily: _kFontFam);
  static const IconData daily = IconData(0xe907, fontFamily: _kFontFam);
  static const IconData education = IconData(0xe908, fontFamily: _kFontFam);
  static const IconData entertainment = IconData(0xe909, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData idea = IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData login = IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData relaxation_01 = IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData relaxation_02 = IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe910, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe911, fontFamily: _kFontFam);
  static const IconData sliders = IconData(0xe912, fontFamily: _kFontFam);
  static const IconData spa = IconData(0xe913, fontFamily: _kFontFam);
  static const IconData sports = IconData(0xe914, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe915, fontFamily: _kFontFam);
}
